# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lifei/Desktop/FPGA/SPWM/PWM/PWM.srcs/sources_1/ip/rom_sin/rom_sin.xci
# IP: The module: 'rom_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lifei/Desktop/FPGA/SPWM/PWM/PWM.srcs/sources_1/ip/rom_sin/rom_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/lifei/Desktop/FPGA/SPWM/PWM/PWM.srcs/sources_1/ip/rom_sin/rom_sin.xci
# IP: The module: 'rom_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lifei/Desktop/FPGA/SPWM/PWM/PWM.srcs/sources_1/ip/rom_sin/rom_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
