set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets Mclock]


set_property PACKAGE_PIN W5 [get_ports CLK]
set_property PACKAGE_PIN U7 [get_ports {display_segout[0]}]
set_property PACKAGE_PIN V5 [get_ports {display_segout[1]}]
set_property PACKAGE_PIN U5 [get_ports {display_segout[2]}]
set_property PACKAGE_PIN V8 [get_ports {display_segout[3]}]
set_property PACKAGE_PIN U8 [get_ports {display_segout[4]}]
set_property PACKAGE_PIN W6 [get_ports {display_segout[5]}]
set_property PACKAGE_PIN W7 [get_ports {display_segout[6]}]
set_property PACKAGE_PIN W4 [get_ports {display_segout[7]}]
set_property PACKAGE_PIN V4 [get_ports {display_segout[8]}]
set_property PACKAGE_PIN U4 [get_ports {display_segout[9]}]
set_property PACKAGE_PIN U2 [get_ports {display_segout[10]}]
set_property PACKAGE_PIN V17 [get_ports en]
set_property PACKAGE_PIN U16 [get_ports Led]
set_property PACKAGE_PIN V16 [get_ports {M_SET[0]}]
set_property PACKAGE_PIN W16 [get_ports {M_SET[1]}]
set_property PACKAGE_PIN W17 [get_ports {M_SET[2]}]
set_property PACKAGE_PIN W15 [get_ports {M_SET[3]}]
set_property PACKAGE_PIN V15 [get_ports {M_SET[4]}]
set_property PACKAGE_PIN R2 [get_ports Mclock]
set_property PACKAGE_PIN U18 [get_ports RST_n]
#set_property IOSTANDARD LVCMOS33 [get_ports {cnt_count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
#set_property IOSTANDARD LVCMOS33 [get_ports {cnt_count[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cnt_count[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cnt_count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_segout[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports Led]
set_property IOSTANDARD LVCMOS33 [get_ports {M_SET[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_SET[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_SET[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_SET[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_SET[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports Mclock]
set_property IOSTANDARD LVCMOS33 [get_ports RST_n]


#set_property IOSTANDARD LVCMOS33 [get_ports {cnt_count[4]}]

#set_property PACKAGE_PIN L1 [get_ports {cnt_count[0]}]
#set_property PACKAGE_PIN P1 [get_ports {cnt_count[1]}]
#set_property PACKAGE_PIN N3 [get_ports {cnt_count[2]}]
#set_property PACKAGE_PIN P3 [get_ports {cnt_count[3]}]
#set_property PACKAGE_PIN U3 [get_ports {cnt_count[4]}]